### ISSUE TITLE
ERROR: Malformed response from weather service

### ISSUE THREAD

**Issue by bronzehedwick** [brianriley/weather-cli#1]
I installed weathercli through pip on Ubuntu 12.10 using Python 2.7.3.

Seemingly no matter what area code I enter (tried 90210, 11219, 07603, 10001), I get the error in this issue's title.

Any idea what might be going wrong?

Thanks!

**Comment by brianriley** [comment]
Looks like Google killed its weather API. I'll work out a replacement soon.

**Comment by bronzehedwick** [comment]
Aw man, Google is killing all their services lately!

Thanks for the prompt reply!

**Comment by nikisix** [comment]
Any fixes to date?   I'm on osx btw

**Comment by brianriley** [comment]
OK, I spent some time finding a new source of weather info. It should be fixed now. You can `pip install weathercli --upgrade` to get the latest. Check out the readme though; you now need to query by location, not postal code, and I also have it reading from an environment variable so you can set your location and not have to type it at the command line.
