### ISSUE TITLE
WEATHER_OPTS="..."

### ISSUE THREAD

**Issue by prologic** [brianriley/weather-cli#3]
Add a `WEATHER_OPTS` that the `weather` CLI respects as default options to be passed.

e.g:

```
export WEATHER_OPTS="--units celsius"
```

**Comment by brianriley** [comment]
I added support for this as `WEATHER_UNITS`. Check out the README, and upgrade to the latest.

**Comment by prologic** [comment]
Sweet :) Thanks!

James Mills / prologic

E: prologic@shortcircuit.net.au
W: prologic.shortcircuit.net.au

**Comment by ghost** [comment]
weathercli approved from Slackware repository and ready for Slackwares users http://slackbuilds.org/repository/14.1/network/weathercli/?search=weathercli .. And thanks for update (celsius) !!!
