### ISSUE TITLE
File name conflict with weather from expect

### ISSUE THREAD

**Issue by richarson** [brianriley/weather-cli#7]
Hi, nice program you have here, unfortunately it overwrote the weather script from expect on my machine (Slackware 14.1, 64 bits). Said script also exists on CentOS 5/6/7.

Is there any chance of renaming your installed script to /usr/bin/weathercli, for example?

TIA.

**Comment by brianriley** [comment]
I believe that this is actually the same script (pretty sure weather-cli included in Slackware). And the version you have in Slackware should be the same as the latest on master here.

**Comment by richarson** [comment]
weather-cli is actually on slackbuilds.org (that's where I installed it from), the other weather is from expect and is a different beast (slp is like 'rpm -qf' or 'dpkg -S' for slackware):

$ slf /usr/bin/weather
expect-5.44.1.15-x86_64-2: usr/bin/weather

Extract of the output from expect's weather:

$ /usr/bin/weather
spawn telnet rainmaker.wunderground.com 3000
Trying 38.102.137.140...
Connected to rainmaker.wunderground.com.

## Escape character is '^]'.

## \*               Welcome to THE WEATHER UNDERGROUND telnet service!            *
-                                                                            *
-   National Weather Service information provided by Alden Electronics, Inc. *
-    and updated each minute as reports come in over our data feed.          *
-                                                                            *
-   **Note: If you cannot get past this opening screen, you must use a       *
-   different version of the "telnet" program--some of the ones for IBM      *
-   compatible PC's have a bug that prevents proper connection.              *
-                                                                            *

## \*           comments: jmasters@wunderground.com                              *

Press Return to continue:

Press Return for menu
or enter 3 letter forecast city code--

```
             WEATHER UNDERGROUND MAIN MENU
            ******************************
             1) U.S. forecasts and climate data
             2) Canadian forecasts
             3) Current weather observations
             4) Ski conditions
             5) Long-range forecasts
             6) Latest earthquake reports
             7) Severe weather
             8) Hurricane advisories
             9) Weather summary for the past month
            10) International data
            11) Marine forecasts and observations
            12) Ultraviolet light forecast
             X) Exit program
             C) Change scrolling to screen
             H) Help and information for new users
             ?) Answers to all your questions
               Selection:C

            OPTION TO CHANGE SCROLLING TO SCREEN
```

**Comment by richarson** [comment]
BTW, there's also another weather program in slackbuilds.org that hinted me about this issue, this is in the README of wheather (http://slackbuilds.org/repository/14.1/misc/weather/):

_SPECIAL NOTE_
This will copy the existing "/usr/bin/weather" script on the system (which 
is part of the "expect" package in Slackware) to "/usr/bin/weather.expect"
while installing the one in this package as "/usr/bin/weather.weather" and
creating a symlink to it from /usr/bin/weather.  If you remove this package
later for whatever reason, then you will need to either reinstall Slackware's
"expect" package, fix the symlink, or remove the symlink and rename the
"/usr/bin/weather.expect" file back to "/usr/bin/weather"

**Comment by ghost** [comment]
Thank you for report.
Fixed:  http://slackbuilds.org/ready/

**Comment by brianriley** [comment]
Well, there it is. :100:

**Comment by richarson** [comment]
Thanks!
